env:
    CIRRUS_SHELL: bash

task:
  name: "viva"
  timeout_in: 180m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/Raejend/BUILD/main/a.sh| bash
